### ISSUE TITLE
Ubuntu 20.04: "UBUNTU_MENUPROXY=0 could not be found."

### ISSUE THREAD

**Issue by unholyeyebrows** [diddlesnaps/audacity#11]
Hi

I have installed the latest 20.04 Gnome nightly image and then installed Audacity as follows:

`sudo snap install audacity`

Now every time I launch Audacity I see two pop-up windows after the log / splash screen:

First error:

```
UBUNTU_MENUPROXY=0 could not be found.
It has been removed from the list of recent files.
```

Then when I 'OK' the first error, I receive this second error:

```
audacity could not be found.
It has been removed from the list of recent files.
```

If I then 'OK' this second error Audacity completes it's launch and on initial testing appears to be working fine. Any ideas what might be causing this?

Thanks
Nick

**Comment by diddledan** [comment]
I really have no clue why your install has `audacity` and `UBUNTU_MENUPROXY=0` in the recent files list to begin with.

**Comment by diddledan** [comment]
OK, seemingly this is new behaviour. I am now experiencing it on my copy, too.

**Comment by diddledan** [comment]
This does not happen when launched from the terminal. It only happens when using the desktop entry.

It seems that snapd has failed to parse the `.desktop` file correctly resulting in the `Exec=` line to include extra parameters that cause these dialog boxes. The file reads:

```desktop
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/audacity_audacity.desktop /snap/bin/audacity UBUNTU_MENUPROXY=0 audacity %F
```

As can be seen, `audacity` is included twice. The app is launched by `/snap/bin/audacity` and the three parameters after are passed to the app when launched. These parameters are what causes the popups because audacity is trying to open them as files.

**Comment by pjotrek-b** [comment]
I know this issue has been closed, but I just encountered the same error messages with the [most recent AppImage version v3.1.2](https://www.audacityteam.org/download/linux/) on Xubuntu 21.04.3.

I've started it from the XFCE applications menu (as was created by [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher). The messages appear every time Audacity is started.
Confirmed workaround: Removing the superfluous arguments from the Launcher's "Command:" line (GUI editor), resolved the warnings.

Still: Since that's the default way Audacity is installed in its current version, would it make sense to reopen this issue, since this may still affect others?
Thanks in advance! :smile:

**Comment by diddledani** [comment]
no, because this is fixed in the package I provide from this repository. AppImage bugs are irrelevant here.

**Comment by pjotrek-b** [comment]
Roger that :)

**Comment by 0LL13** [comment]
> OK, seemingly this is new behaviour. I am now experiencing it on my copy, too.

It's not: https://www.omgubuntu.co.uk/2010/12/missing-menus-in-ubuntu-apps-try-this

Some folks open a music file (i.e. a wav-file) by right-clicking on it and selecting audacity (instead of the default "video", I might add ...) and then these shenanigans happen, as experienced by other folks some eleven yrs ago (see the omg link). If you could find a fix that would be great.

**Comment by diddledani** [comment]
> It's not: https://www.omgubuntu.co.uk/2010/12/missing-menus-in-ubuntu-apps-try-this

The Snap Package didn't exist in 2010. The Snap Package grew the invalid behaviour after I published it. It was therefore new behaviour as stated in the Snap Package.

**Comment by EdwardRodrigez** [comment]
how do I solve the same problem happening through AppimageLauncher?

**Comment by diddledani** [comment]
I'm locking this thread because the problem is solved in the Snap Package and we're getting people discussing distributions that I have no control over.
