### ISSUE TITLE
permission has not been granted for audacity!

### ISSUE THREAD

**Issue by mehdiMj-ir** [diddlesnaps/audacity#23]
Hi, I install `audacity` stable version from `snap` on `Ubuntu 20.10` and there is problem. when I start program a popup showed up and says:
![popup](https://user-images.githubusercontent.com/20270329/115679697-18077400-a368-11eb-9f48-dc54d1e6fd36.png) 
when I click on *permission has been granted* nothing happens :(
```
(yad:59950): Gtk-WARNING **: 12:37:27.411: GTK+ module /snap/audacity/756/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 12:37:27.411: Failed to load module "canberra-gtk-module"
```
I searched for and I installed `sudo apt install libcanberra-gtk-module libcanberra-gtk3-module` but it's already installed.
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcanberra-gtk3-module is already the newest version (0.30-7ubuntu2).
libcanberra-gtk3-module set to manually installed.
libcanberra-gtk-module is already the newest version (0.30-7ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
What should I do?!

**Comment by Petros626** [comment]
did you solved it ?

**Comment by mehdiMj-ir** [comment]
Actually no, should I cloud the issue?

**Comment by lucyllewy** [comment]
Hi, I'm sorry you're having an issue.

- Did you grant the `alsa` permission as directed by the instructions in the popup before clicking the `Permission has been granted` button?
- If you said no to the question above, does Audacity start if you grant the permission now and then restart audacity?

I will try to investigate tomorrow. However, you can get a somewhat functional audacity by piping through PulseAudio instead of Alsa by clicking either of the "Start and..." buttons, or by adding a file at `~/snap/audacity/common/Always use PulseAudio` with the following single line within it:

```bash
ALWAYS_USE_PULSEAUDIO=1
```

**Comment by mehdiMj-ir** [comment]
Thanks for your respond, I don't use `audacity` over a year and that was an experience I tried to share.

**Comment by Petros626** [comment]
> Actually no, should I close the issue?

I can tell you how to solve the error with the .so file. In my case I used 4 commands and after that this errors disappeared. But I got another with `libgail` and `libatk-bridge`.
